//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SO.PictManager.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblGroup
    {
        public int GroupId { get; set; }
        public string Description { get; set; }
        public System.DateTime InsertedDateTime { get; set; }
        public System.DateTime UpdatedDateTime { get; set; }
    }
}
